### ISSUE TITLE
Portable packages installed in user scope are removed from PATH after upgrading them

### ISSUE THREAD

**Issue by soredake** [microsoft/winget-cli#4044]
### Brief description of your issue

Portable packages installed in user scope are removed from PATH after upgrading them.

### Steps to reproduce

1) `winget install yt-dlp.yt-dlp -v 2023.11.16` → yt-dlp added to PATH
2) `winget install gyan.ffmpeg -v 6.1` → ffmpeg added to PATH
3) `winget upgrade yt-dlp.yt-dlp` → yt-dlp removed from PATH
4) `winget upgrade gyan.ffmpeg` → ffmpeg removed from PATH

### Expected behavior

Portable packages should not be removed from PATH after upgrading them.

### Actual behavior

Portable packages are removed from PATH after upgrading them.

### Environment

```shell
Windows Package Manager (Preview) v1.7.3481-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.3481.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

**Comment by AzureArmageddon** [comment]
Able to replicate. Here's my `winget --info`:

```
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

The above says Windows 10 or something but I'm on Windows 11 so here's the OS version information:

```
Edition	Windows 11 Home
Version	22H2
Installed on	‎22/‎11/‎22
OS build	22621.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0
```

**Comment by curioussabhi** [comment]
I also have this issue. Had to remove and reinstall to get it added to PATH again.

**Comment by akulbe** [comment]
@josh-hemphill Is this only happen on upgrade? I'm having things not showing up on $PATH even on new install.

**Comment by josh-hemphill** [comment]
> @josh-hemphill Is this only happen on upgrade? I'm having things not showing up on $PATH even on new install.

For me, yes, fresh installs do show up in path, if it's not, maybe it's package specific. For me I only noticed it with `pnpm`

**Comment by Sammy-T** [comment]
I'm also having this issue while trying to update pnpm. Is someone able to confirm whether this is a winget issue or a pnpm issue?

**Comment by auanasgheps** [comment]
I have this issue as well. Anyone from the team?

**Comment by auanasgheps** [comment]
Hello, commenting again because I just encountered this issue, again.
Updated gallery-dl and its path was removed. 
winget v1.8.1911. 
I can always replicate the issue.

**Comment by hong-chan** [comment]
@ryfu-msft

**Comment by grolongo** [comment]
It happens during install as well, not just upgrading. The problem occurs because `%LOCALAPPDATA%\Microsoft\WinGet\Links` gets removed from `$PATH` after installing some packages. It's like, when installing package A it sees `$PATH` doesn't contain `Links` folder, so it adds it, which is expected. But when you install package B, it sees `$PATH` has `Links` already in it and decides to remove it. Also it looks like it's WinGet doing these shenanigans and not the packages themselves. It happens randomly too...

**Comment by HammerPoppy** [comment]
voting this up

**Comment by SuborbitalSentinel** [comment]
Same problem. Any time I do a `winget update --all`, any cli tool I've installed get's removed from PATH. Incredibly annoying.

**Comment by auanasgheps** [comment]
To anyone having this issue: please upvote the OP so it gets more visibility. I think the winget team hasn't seen this yet.

**Comment by Demitrix2k** [comment]
I so want this to be fixed, i have to manually uninstall and reinstall for the cli tools i use to "fix" this issue that always happens when there is an update.

**Comment by adrianghc** [comment]
I believe this is fixed with v1.10.390? I haven't encountered this right now upgrading two such packages.

**Comment by adrianghc** [comment]
I don't think I'm seeing this anymore with v1.10.390?

**Comment by auanasgheps** [comment]
Just got the issue again by upgrading gallery-dl to the latest version.
Using winget 1.10.390 on Windows 10.

**Comment by owenlamont** [comment]
I get this problem consistently when upgrading terragrunt with winget 1.11.400

**Comment by felipecrs** [comment]
This issue seems to be still happening sporadically. Happened to me a few times in the last weeks, but just happened again today.

```console
$ winget --version
v1.29.140-preview
```

I cannot find a way to reproduce it reliably, but today I ran a `winget upgrade --all`, which upgraded `rclone.rclone` and broke it (I did reload `PATH`).

To fix it, I had to `winget uninstall rclone.rclone && winget install rclone.rclone`.
