### ISSUE TITLE
winget upgrade-available reports multiple CUDA updates, even if using latest version

### ISSUE THREAD

**Issue by eabase** [microsoft/winget-cli#4415]
### Brief description of your issue

I installed the latest Nvidia.CUDA package/drivers and now winget reports multiple updates available for the same package.

```powersehll
# winget list --upgrade-available

Name                     Id          Version  Available Source
--------------------------------------------------------------
NVIDIA CUDA Toolkit      Nvidia.CUDA 12.4     12.4.1    winget
NVIDIA CUDA Toolkit 12.3 Nvidia.CUDA 12.3.2   12.4.1    winget
NVIDIA CUDA Toolkit 12.4 Nvidia.CUDA > 12.3.2 12.4.1    winget

3 upgrades available.
```

### Steps to reproduce

Install old version, unless you already have one. 
Then install the latest version.

### Expected behavior

That the package is reported as up-to-date / latest, and not shown when using the `--upgrade-available` 

### Actual behavior

Showing multiple available versions for the same package id, even if already at latest.

### Environment

**`winget --info`**

```shell
Windows Package Manager v1.7.11132
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3447
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11132.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```
```

**Comment by eabase** [comment]
Your AI have correctly identified several similar issues dating back ~3 years, so why haven't this annoyance been fixed?

**Comment by denelon** [comment]
We've started working on these "side-by-side" types of issues. The latest WinGet 1.8-preview has an experimental feature which can be enabled and may improve the experience here.

**Comment by eabase** [comment]
> We've started working on these "side-by-side" types of issues. The latest WinGet 1.8-preview has an experimental feature which can be enabled and may improve the experience here.

Great! How can I test the new preview?

(Sorry, I can't recall how to install the different version.)

**Comment by denelon** [comment]
You can install the preview versions here at GitHub in the releases section. The release notes also cover which experimental features are available. You can run `winget settings -?` in the client to see the help and get a link to the settings available for the client.

**Comment by eabase** [comment]
Yes, I tried by installing the 1.8-preview. 

Indeed the issues with multiple CUDA versions were gone, and also the `Microsoft.DotNet.DesktopRuntime.6` issue. 

To Install winget *preview*, do this:

```powershell
# 0. Check winget features
winget features

# 1. Download "-preview" from:
https://github.com/microsoft/winget-cli/releases

# 2. Run (as admin):
Add-AppxPackage -Path '.\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle'

# 3. Change feature settings:
winget settings

# 4. Add:
"experimentalFeatures": {
        "sideBySide": true
    }

# Check
winget --info

# To Revert, download & run (the non-preview version):
Add-AppxPackage -Path '.\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.1.7.11132.msixbundle' -ForceUpdateFromAnyVersion

```

However, I had to revert because the output formatting of `winget list` was awful, where all the `Id`s had been replaced with `MSIX/....` something.

**Comment by eabase** [comment]
**OT Warning!**

This brings up another (OT) issue.  
Why can't we install whatever version we like using the `id` and `Version/Available` strings? 
That would make much more sense, than having to run `Add-AppxPackage`.

One would expect something like the following to work:
```powershell
winget install -i -e "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle" -v '1.7.11132`
```

**Comment by fehrin1** [comment]
I have the same problem or to state it clear: I have only CUDA 12.4.1 installed and get with winget update (upgrade)
NVIDIA CUDA Toolkit 12.4  Nvidia.CUDA    > 12.3.2         12.4.1           winget
So there is a flaw in detecting the installed version, is this corrected in some winget version resp. will it be fixed in future versions?

**Comment by fehrin1** [comment]
As of today winget correctly detects the installed 12.4.1 version, consequently no update is suggested anymore (no multiple / side-by-side installation present).

**Comment by eabase** [comment]
@fehrin1 
> _As of today winget correctly detects..._

What do you mean? The latest release was 2 weeks ago, with `1.7.11261`, so what are you using?
(Not fixed for this version.)

**Comment by fehrin1** [comment]
> @fehrin1
> 
> > _As of today winget correctly detects..._
> 
> What do you mean? The latest release was 2 weeks ago, with `1.7.11261`, so what are you using? (Not fixed for this version.)

I have this version too and for me CUDA 12.4.1 is correctly detected. The multi version (side by side) issue is most probably still present. Just guessing probably the version info downloaded by "winget (source) update" got updated.

**Comment by denelon** [comment]
WinGet 1.8 has the side-by-side improvements enabled, and the earlier bug reported has also been fixed. 
Has the issue here been resolved?

**Comment by fehrin1** [comment]
> WinGet 1.8 has the side-by-side improvements enabled, and the earlier bug reported has also been fixed. Has the issue here been resolved?

There are no CUDA issues left, but i still get the spurious recommendation (i made a separate winget issue about this)
C:\Users\FEH01589>winget update
Name                      ID             Version          Verfügbar        Quelle
----------------------------------------------------------------------------------
Microsoft OneNote - de-de XPFFZHVGQWWLHB 16.0.16731.20716 16.0.17231.20236 msstore
1 Aktualisierungen verfügbar.
My guess is that there is some information base for software versions which needs an update too.
Personally i would exclude OneNote from winget updates, it is only a placeholder for a full blown Office 365 installation.

**Comment by mdanish-kh** [comment]
> Personally i would exclude OneNote from winget updates

Have you tried `winget pin add --id XPFFZHVGQWWLHB`? If you experience further problems, you can open up a separate issue for it

**Comment by fehrin1** [comment]
> > Personally i would exclude OneNote from winget updates
> 
> Have you tried `winget pin add --id XPFFZHVGQWWLHB`? If you experience further problems, you can open up a separate issue for it

If the (OnenNote i.e. non CUDA) issue really disturbed me i could surely smash it with a hammer. But i prefer to wait for a real solution. In any case the CUDA issue is no longer present for me (but i am not the original issuer).
