### ISSUE TITLE
Whether downloading or searching, wingent doesn't work properly. Is it caused by network problems?

### ISSUE THREAD

**Issue by AirBashX** [microsoft/winget-cli#611]
# Brief description of your issue
Whether it is downloading or searching, wingent can't work properly.
Is it caused by network problems?

# Steps to reproduce

` winget search `7Zip or `winget install 7Zip`
# Expected behavior

search or install
# Actual behavior

Loading all the time, no reaction

# Environment
```none
Windows Package Manager v0.2.2521 预览
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.19041.572
程序包: Microsoft.DesktopAppInstaller v1.11.2521.0

链接
------------------------------------------
隐私声明  https://aka.ms/winget-privacy
许可协议  https://aka.ms/winget-license
第三方声明 https://aka.ms/winget-3rdPartyNotice
主页    https://aka.ms/winget
```

**Comment by denelon** [comment]
We had some problems last weekend. If you have the "current" index (`winget source update`) it should be working. I haven't gotten any other reports from users.

**Comment by megamorf** [comment]
Also, note that since you seem to be located in China that some installer downloads can fail due to slow download speeds and package loss caused by the Great Firewall of China.

**Comment by AirBashX** [comment]
> Also, note that since you seem to be located in China that some installer downloads can fail due to slow download speeds and package loss caused by the Great Firewall of China.
> 
> Also, please note that since you appear to be in China, some installer downloads may fail due to slow downloads and loss of packages due to the Chinese firewall.

Firewall really bothers me. It should be caused by firewall and network problems. My device has returned to normal

**Comment by marcinsmialek** [comment]
Reopen?
This is still an issue. When behind corporate firewall, the downloads become extremely slow, maybe even getting slower and slower during downloads of bigger files. Docker Desktop upgrade may serve as an example, when I tried it a couple of times, and I had to stop after a few hours. Downloading via browser is snappy. Moreover, it didn't restart even smaller downloads after network reconnect, and I couldn't find an option to resume downloads.

**Comment by denelon** [comment]
@marcinsmialek have you tried switching to "wininet" in your network download [settings](https://aka.ms/winget-settings/)?

**Comment by marcinsmialek** [comment]
@denelon As I reported above, `wininet` worked.

The problem is that the defaults are not reliable in some cases, there's no fallback, no auto detection / fix, no resume functionality, no verbose mode, and the diagnostics are troublesome. One has to guess that the downloader mode has to be changed, try again, then change again to wininet, and try again. There are references to "do" and "wininet" doc pages, but there are no diagnostic steps described. What are the end-user consequences of using these options? What can go wrong, and when? Which one is the default (without inspecting source code)?

winget does many things well, but there are silent failures

**Comment by denelon** [comment]
@marcinsmialek we've got another release in the works. It includes a [fallback to wininet](https://github.com/microsoft/winget-cli/pull/1138) in the event Delivery Optimization (DO) download fails.

https://aka.ms/winget-settings is referenced in `winget settings -?`. This problem wasn't detected in our initial testing. As soon as it started appearing we started a deep dive. The change to settings was the best "work around" we could provide while we implement the fallback.
